#!/bin/bash

SOURCE=$1
PAGE=$2

# https://m.pqshu.cc/fanhua/2267221.html
# 001

wget -O $PAGE.0 $SOURCE
iconv -f gbk -t utf-8 $PAGE.0 > $PAGE.1
echo '<meta http-equiv="Content-Type" content="application/xhtml+xml; charset=UTF-8" />' > $PAGE.2
cat $PAGE.1 | grep -A1 '<div class="page-content font-large">' | grep -v '<div class="page-content font-large">' >> $PAGE.2
sed -i 's|<font color="blue">.*||g' $PAGE.2
cat $PAGE.2 | sed 's|<br />|\n|g' | grep . > $PAGE.3
sed -i 's|.*age.*||g' $PAGE.3
cat $PAGE.3 | grep . > $PAGE.4
sed -i 's|<p>|<pre>|g' $PAGE.4
cat $PAGE.4 | grep -v ^' ' > $PAGE.html
rm -f $PAGE.[0-4]
