#!/bin/bash

# wait MOMENT (in secound) till ./rpipe process count greater than MAX
MOMENT=9
MAX=4


# to bring up the pipe reader at background:	./rpipe &
# or better with:				nohup /var/nginx/html/.ent/000/rpipe &

pipe=task_pipe

trap "rm -f $pipe" EXIT

if [[ ! -p $pipe ]]; then
    mkfifo $pipe
fi

while true
do
    if read line <$pipe; then
        if [[ "$line" == 'quit' ]]; then
            break
        fi

	# wait MOMENT (in secound) till ./rpipe process count less than MAX
	# while [ $(ps aux|grep -v grep|grep -c '/bin/bash ./rpipe') -gt $MAX ];do sleep $MOMENT;done

	while [ $(ps aux|grep -v grep|grep -c 'rpipe') -gt $MAX ];do sleep $MOMENT;done
	# the following line is really doing something by reading the argument in the task_pipe named pipe
        ./q $line  > /dev/null 2>&1 &

    fi
done

echo "Reader exiting"
