#!/bin/bash

# write something into named pipe task_pipe
# the reader will take the string as argument to pass to script q to process
# usage:
# ./wpipe URL (in this use case)
# ./wpipe quit (to quit the reader running in the background)
# monitor pipe processors:	watch -n 3 "ps aux|grep -v grep|grep 'wget\|pipe'"

pipe=task_pipe

if [[ ! -p $pipe ]]; then
    echo "Reader not running"
    exit 1
fi

if [[ "$1" ]]; then
    echo "$1" >$pipe
else
    echo "Hello from $$" >$pipe
fi
